CREATE TABLE IF NOT EXISTS vehiculos_ev (
    id SERIAL PRIMARY KEY,
    combustible VARCHAR(100),
    estado VARCHAR(100),
    fecha_registro VARCHAR(100),
    anio_registro INT,
    clase VARCHAR(100),
    departamento VARCHAR(100),
    cantidad DOUBLE PRECISION,
    marca_ev_colombia VARCHAR(255),
    fabricante_bateria_real VARCHAR(255),
    tecnologia_bateria VARCHAR(255),
    capacidad_kwh DOUBLE PRECISION,
    voltaje_v DOUBLE PRECISION,
    autonomia_km DOUBLE PRECISION,
    consumo_wh_km DOUBLE PRECISION,
    potencia_carga_dc_kw DOUBLE PRECISION,
    corriente_carga_a DOUBLE PRECISION,
    impacto_red VARCHAR(255),
    transformador_kva DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS activos_hidraulicos (
    id SERIAL PRIMARY KEY,
    nombre_activo VARCHAR(255),
    nombre VARCHAR(255),
    operador VARCHAR(255),
    estado VARCHAR(100),
    fecha_puesta_en_operacion_fpo VARCHAR(100),
    fecha_de_puesta_en_operacion_fpo VARCHAR(100),
    modo_operacion VARCHAR(100),
    modo_de_operacion VARCHAR(100),
    tipo_activo_hidraulico VARCHAR(100),
    tipo_de_proceso_productivo VARCHAR(100),
    rampas_si_no VARCHAR(20),
    unidades_hidraulicas DOUBLE PRECISION,
    capacidad_hidraulica DOUBLE PRECISION,
    capacidad_efectiva_neta_mw DOUBLE PRECISION,
    factor_conversion_hidraulico_mw_m3_s DOUBLE PRECISION,
    factor_de_conversion_hidraulico_mw_m3_s DOUBLE PRECISION,
    clasificacion VARCHAR(100),
    minimo_obligatorio_si_no VARCHAR(20),
    arranque_autonomo_si_no VARCHAR(20),
    departamento VARCHAR(100),
    municipio VARCHAR(100),
    subarea VARCHAR(100),
    latitud DOUBLE PRECISION,
    longitud DOUBLE PRECISION
);
