CREATE TABLE IF NOT EXISTS vehiculos_ev (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    combustible VARCHAR(100),
    estado VARCHAR(100),
    fecha_registro VARCHAR(100),
    anio_registro INT,
    clase VARCHAR(100),
    departamento VARCHAR(100),
    cantidad DOUBLE,
    marca_ev_colombia VARCHAR(255),
    fabricante_bateria_real VARCHAR(255),
    tecnologia_bateria VARCHAR(255),
    capacidad_kwh DOUBLE,
    voltaje_v DOUBLE,
    autonomia_km DOUBLE,
    consumo_wh_km DOUBLE,
    potencia_carga_dc_kw DOUBLE,
    corriente_carga_a DOUBLE,
    impacto_red VARCHAR(255),
    transformador_kva DOUBLE
);

CREATE TABLE IF NOT EXISTS activos_hidraulicos (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre_activo VARCHAR(255),
    nombre VARCHAR(255),
    operador VARCHAR(255),
    estado VARCHAR(100),
    fecha_puesta_en_operacion_fpo VARCHAR(100),
    fecha_de_puesta_en_operacion_fpo VARCHAR(100),
    modo_operacion VARCHAR(100),
    modo_de_operacion VARCHAR(100),
    tipo_activo_hidraulico VARCHAR(100),
    tipo_de_proceso_productivo VARCHAR(100),
    rampas_si_no VARCHAR(20),
    unidades_hidraulicas DOUBLE,
    capacidad_hidraulica DOUBLE,
    capacidad_efectiva_neta_mw DOUBLE,
    factor_conversion_hidraulico_mw_m3_s DOUBLE,
    factor_de_conversion_hidraulico_mw_m3_s DOUBLE,
    clasificacion VARCHAR(100),
    minimo_obligatorio_si_no VARCHAR(20),
    arranque_autonomo_si_no VARCHAR(20),
    departamento VARCHAR(100),
    municipio VARCHAR(100),
    subarea VARCHAR(100),
    latitud DOUBLE,
    longitud DOUBLE
);
